const fs = require('fs');
const path = require('path');

const assetsDir = path.join(__dirname, '../assets');
const outputFile = path.join(__dirname, '../src/assets.ts');

function readFile(filename) {
  const filePath = path.join(assetsDir, filename);
  if (fs.existsSync(filePath)) {
    return fs.readFileSync(filePath, 'utf8').replace(/`/g, '\\`').replace(/\$/g, '\\$');
  }
  return '';
}

const assets = {
  en: {
    prompt: readFile('prompt.md'),
    train: readFile('train.md'),
    error_hint: readFile('error_hint.md'),
  },
  zh: {
    prompt: readFile('prompt_zh.md'),
    train: readFile('train_zh.md'),
    error_hint: readFile('error_hint_zh.md'),
  }
};

const content = `/**
 * This file is auto-generated by scripts/generate-assets.js
 * Do not edit this file directly.
 */
export const ASSETS = {
  en: {
    prompt: \`${assets.en.prompt}\`,
    train: \`${assets.en.train}\`,
    error_hint: \`${assets.en.error_hint}\`,
  },
  zh: {
    prompt: \`${assets.zh.prompt}\`,
    train: \`${assets.zh.train}\`,
    error_hint: \`${assets.zh.error_hint}\`,
  }
};
`;

fs.writeFileSync(outputFile, content);
console.log('Assets generated successfully at ' + outputFile);
