import spawn from 'cross-spawn';
import * as path from 'path';
import * as fs from 'fs';

export class NodeInstaller {
  constructor(private rootDir: string) {}

  /**
   * Install a Node.js based MCP service into a sandbox directory.
   * This creates a dedicated package.json for the service to avoid version conflicts.
   */
  async install(serviceId: string, pkgName: string, version: string = 'latest'): Promise<boolean> {
    const serviceDir = path.join(this.rootDir, 'services', serviceId);
    
    if (!fs.existsSync(serviceDir)) {
      fs.mkdirSync(serviceDir, { recursive: true });
    }

    const proxyPkg = {
      name: `${serviceId.replace(/[^a-zA-Z0-9-]/g, '-')}-proxy`,
      version: "0.0.0",
      private: true,
      description: "Auto-generated by @mcp-kit/core",
      dependencies: {
        [pkgName]: version
      }
    };

    fs.writeFileSync(
      path.join(serviceDir, 'package.json'),
      JSON.stringify(proxyPkg, null, 2)
    );

    console.log(`[Installer] Starting npm install for ${pkgName} in ${serviceDir}...`);

    return new Promise((resolve, reject) => {
      const child = spawn('npm', ['install', '--loglevel=error'], {
        cwd: serviceDir,
        stdio: 'inherit',
        shell: true
      });

      child.on('close', (code) => {
        if (code === 0) {
          console.log(`[Installer] Successfully installed ${pkgName}`);
          resolve(true);
        } else {
          const errorMsg = `npm install failed with code ${code}`;
          console.error(`[Installer] ${errorMsg}`);
          reject(new Error(errorMsg));
        }
      });

      child.on('error', (err) => {
        console.error(`[Installer] Process error:`, err);
        reject(err);
      });
    });
  }

  checkInstalled(serviceId: string): boolean {
    const serviceDir = path.join(this.rootDir, 'services', serviceId);
    return fs.existsSync(path.join(serviceDir, 'node_modules'));
  }
}
